services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: prep
      POSTGRES_PASSWORD: prep
      POSTGRES_DB: prep_api
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql:ro

volumes:
  pgdata:
